name: XSS Security Scan

on:
  workflow_dispatch:   # Запуск вручную

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install XSStrike
        run: |
          python3 -m pip install --upgrade pip
          pip install xsstrike

      - name: Run XSS Scan
        run: |
          echo "Scanning: http://localhost:3000"
          xsstrike -u "http://localhost:3000" --crawl > xss-report.txt

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: xsstrike-report
          path: xss-report.txt
